-- Seed data: constraint_config, time_matrix, academic catalog (autumn + winter offerings).
-- Apply after 001_schema.sql, then run 003_rooms_actual.sql for room inventory.

-- Default batch size when CSV does not specify strength
INSERT INTO constraint_config (key, value_json) VALUES
    ('default_batch_size', '60'::jsonb),
    ('max_subjects_per_faculty', '3'::jsonb),
    ('max_lectures_same_course_per_day_per_batch', '1'::jsonb),
    ('soft_no_consecutive_faculty', 'true'::jsonb),
    ('csp_timeout_seconds', '120'::jsonb)
ON CONFLICT (key) DO NOTHING;

-- Time matrix (Mon–Fri; lunch = blackout)
INSERT INTO time_matrix (day_of_week, start_time, end_time, slot_group, is_blackout)
VALUES
    ('Mon', '08:00', '09:00', 'TEACHING', FALSE),
    ('Mon', '09:00', '10:00', 'TEACHING', FALSE),
    ('Mon', '10:00', '11:00', 'TEACHING', FALSE),
    ('Mon', '11:00', '12:00', 'TEACHING', FALSE),
    ('Mon', '12:00', '13:00', 'TEACHING', FALSE),
    ('Mon', '13:00', '14:00', 'BLACKOUT', TRUE),
    ('Mon', '14:00', '15:00', 'TEACHING', FALSE),
    ('Tue', '08:00', '09:00', 'TEACHING', FALSE),
    ('Tue', '09:00', '10:00', 'TEACHING', FALSE),
    ('Tue', '10:00', '11:00', 'TEACHING', FALSE),
    ('Tue', '11:00', '12:00', 'TEACHING', FALSE),
    ('Tue', '12:00', '13:00', 'TEACHING', FALSE),
    ('Tue', '13:00', '14:00', 'BLACKOUT', TRUE),
    ('Tue', '14:00', '15:00', 'TEACHING', FALSE),
    ('Wed', '08:00', '09:00', 'TEACHING', FALSE),
    ('Wed', '09:00', '10:00', 'TEACHING', FALSE),
    ('Wed', '10:00', '11:00', 'TEACHING', FALSE),
    ('Wed', '11:00', '12:00', 'TEACHING', FALSE),
    ('Wed', '12:00', '13:00', 'TEACHING', FALSE),
    ('Wed', '13:00', '14:00', 'BLACKOUT', TRUE),
    ('Wed', '14:00', '15:00', 'TEACHING', FALSE),
    ('Thur', '08:00', '09:00', 'TEACHING', FALSE),
    ('Thur', '09:00', '10:00', 'TEACHING', FALSE),
    ('Thur', '10:00', '11:00', 'TEACHING', FALSE),
    ('Thur', '11:00', '12:00', 'TEACHING', FALSE),
    ('Thur', '12:00', '13:00', 'TEACHING', FALSE),
    ('Thur', '13:00', '14:00', 'BLACKOUT', TRUE),
    ('Thur', '14:00', '15:00', 'TEACHING', FALSE),
    ('Fri', '08:00', '09:00', 'TEACHING', FALSE),
    ('Fri', '09:00', '10:00', 'TEACHING', FALSE),
    ('Fri', '10:00', '11:00', 'TEACHING', FALSE),
    ('Fri', '11:00', '12:00', 'TEACHING', FALSE),
    ('Fri', '12:00', '13:00', 'TEACHING', FALSE),
    ('Fri', '13:00', '14:00', 'BLACKOUT', TRUE),
    ('Fri', '14:00', '15:00', 'TEACHING', FALSE)
ON CONFLICT (day_of_week, start_time) DO NOTHING;

-- Academic catalog (faculty, courses, batches, maps)
-- Faculty
INSERT INTO faculty (short_name, full_name) VALUES ('AG', 'AG') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('AJ', 'AJ') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('AKM', 'AKM') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('AKR', 'AKR') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('AM', 'AM') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('AMM', 'AMM') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('AR', 'AR') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('AR2', 'AR2') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('AT', 'AT') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('AT2', 'AT2') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('BC', 'BC') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('BG', 'BG') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('BK', 'BK') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('BM', 'BM') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('CJ', 'CJ') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('DKG', 'DKG') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('GD', 'GD') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('GP', 'GP') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('GS', 'GS') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('HP', 'HP') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('MK', 'MK') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('MK2', 'MK2') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('MKG', 'MKG') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('MKR', 'MKR') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('MS', 'MS') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('MT', 'MT') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('MVJ', 'MVJ') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('NKS', 'NKS') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('PA', 'PA') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('PB', 'PB') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('PK', 'PK') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('PK2', 'PK2') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('PKS', 'PKS') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('PMJ', 'PMJ') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('PhD Scholar', 'PhD Scholar') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('RC', 'RC') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('RG', 'RG') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('RLD', 'RLD') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('RM', 'RM') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('RM2', 'RM2') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('RP', 'RP') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('SB', 'SB') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('SB2', 'SB2') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('SDG', 'SDG') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('SJ', 'SJ') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('SK', 'SK') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('SM', 'SM') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('SP', 'SP') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('SR', 'SR') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('SS', 'SS') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('ST', 'ST') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('TBD', 'TBD') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('TKM', 'TKM') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('VS', 'VS') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('VSP', 'VSP') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('YA', 'YA') ON CONFLICT (short_name) DO NOTHING;
INSERT INTO faculty (short_name, full_name) VALUES ('YV', 'YV') ON CONFLICT (short_name) DO NOTHING;

-- Courses (first occurrence wins for duplicate codes across semesters)
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('CS201', 'Introductory Computational Physics', 3, 0, 3, 4.5, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('CS301', 'High Performance Computing', 3, 0, 3, 4.5, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('CS302', 'Modeling and Simulation', 3, 0, 3, 4.5, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('CS374', 'Computational and Numerical Methods', 3, 0, 3, 4.5, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('CT204', 'Signals and Systems', 3, 0, 2, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('CT216', 'Introduction to Communication Systems', 3, 0, 2, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('CT303', 'Digital Communication', 3, 0, 2, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('ED111', 'Engineering Mathematics I', 3, 1, 0, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('ED112', 'Engineering Physics', 3, 1, 0, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('ED121', 'Engineering Mathematics II', 3, 1, 0, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('EL111', 'Basic Electronic Circuits', 3, 0, 2, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('EL203', 'Embedded Hardware Design', 3, 0, 2, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('HM106', 'Approaches to Indian Society', 3, 0, 0, 3.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('HM116', 'Principles of Economics', 3, 0, 0, 3.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('HM216', 'Science-Technology-and Society', 3, 0, 0, 3.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('IC101', 'Introduction to ICT', 1, 0, 2, 2.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('IC121', 'Digital Logic and Computer Organization', 3, 0, 2, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('IE402', 'Optimization', 3, 0, 2, 4.0, 'ICT & Technical Elective') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('IE403', 'Human Computer Interaction', 3, 0, 2, 4.0, 'ICT & Technical Elective-MnC Elective') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('IE404', 'Digital Image Processing', 3, 0, 2, 4.0, 'ICT & Technical Elective') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('IE406', 'Machine Learning', 3, 0, 2, 4.0, 'ICT & Technical Elective (RAS minor)') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('IE407', 'Internet of Things', 3, 0, 2, 4.0, 'ICT & Technical Elective (RAS minor)') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('IE408', 'Control of Autonomous Systems', 3, 0, 2, 4.0, 'ICT & Technical Elective (RAS minor)') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('IE410', 'Introduction to Robotics', 3, 0, 2, 4.0, 'ICT & Technical Elective (RAS minor + Honours Cat)') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('IE411', 'Operating Systems', 3, 0, 2, 4.0, 'ICT & Technical Elective') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('IT112', 'Introduction to Programming', 3, 0, 0, 3.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('IT205', 'Data Structures', 3, 0, 0, 3.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('IT206', 'Data Structure Lab using OOP', 1, 0, 2, 2.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('IT214', 'Database Management System', 3, 0, 2, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('IT216', 'Design and Analysis of Algorithms', 3, 0, 2, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('IT227', 'Computer Systems Programming', 3, 0, 2, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('IT304', 'Computer Networks', 3, 0, 2, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('IT314', 'Software Engineering', 3, 0, 2, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('IT422', 'Models of Computation', 3, 0, 0, 3.0, 'Technical Elective (Honours Cat)') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC111', 'Mathematical-Algorithmic-and Computational Thinking', 3, 1, 0, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC112', 'Computer Organization and Programming', 3, 0, 0, 3.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC116', 'Digital Logic Design', 1, 0, 2, 2.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC122', 'Object Oriented Programming', 2, 0, 2, 3.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC123', 'Discrete Mathematics', 3, 1, 0, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC124', 'Data Structures and Algorithms', 3, 0, 2, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC125', 'Functions of Single Variable and ODEs', 3, 1, 0, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC211', 'Functions of Several Variables and PDEs', 3, 1, 0, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC212', 'Database Management Systems', 3, 0, 2, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC213', 'Design and Analysis of Algorithms', 3, 1, 0, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC214', 'Operating Systems (along with IE411)', 3, 0, 2, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC215', 'Linear Algebra', 3, 1, 0, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC216', 'Probability and Random Processes', 3, 1, 0, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC221', 'Mathematical Statistics', 3, 1, 0, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC222', 'Real and Complex Analysis', 3, 1, 0, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC223', 'Theory of Computation', 3, 1, 0, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC224', 'Parallel and Distributed Algorithms', 3, 1, 0, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC225', 'Numerical and Computational Methods', 3, 0, 2, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC226', 'Environmental Studies', 2, 0, 0, 2.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC311', 'Mathematical Optimization', 3, 1, 0, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC312', 'Modelling and Simulation', 3, 0, 2, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC313', 'Algebraic Structures', 3, 1, 0, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC314', 'Principles of Economics', 3, 0, 0, 3.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('MC321', 'Machine Learning', 3, 0, 2, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('PC110', 'Language and Literature', 3, 0, 0, 3.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('SC107', 'Calculus', 3, 1, 0, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('SC205', 'Discrete Mathematics', 3, 1, 0, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('SC217', 'Electromagnetic Theory', 3, 1, 0, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('SC223', 'Linear Algebra', 3, 1, 0, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('SC224', 'Probability and Statistics', 3, 1, 0, 4.0, 'Core') ON CONFLICT (code) DO NOTHING;
INSERT INTO course (code, title, lecture_hours, tutorial_hours, practical_hours, credits, course_type) VALUES ('SC407', 'Environmental Science', 3, 0, 0, 3.0, 'Core') ON CONFLICT (code) DO NOTHING;

-- Student batches (default batch_size = 60)
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('CS-S2', 'CS', 2, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('CS-S3', 'CS', 3, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('CS-S4', 'CS', 4, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('CS-S5', 'CS', 5, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('CS-S6', 'CS', 6, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('EVD-S1', 'EVD', 1, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('EVD-S2', 'EVD', 2, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('EVD-S3', 'EVD', 3, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('ICTA-S1', 'ICTA', 1, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('ICTA-S2', 'ICTA', 2, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('ICTA-S3', 'ICTA', 3, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('ICTA-S4', 'ICTA', 4, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('ICTA-S5', 'ICTA', 5, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('ICTA-S6', 'ICTA', 6, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('ICTB-S1', 'ICTB', 1, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('ICTB-S2', 'ICTB', 2, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('ICTB-S3', 'ICTB', 3, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('ICTB-S4', 'ICTB', 4, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('ICTB-S5', 'ICTB', 5, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('ICTB-S6', 'ICTB', 6, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('MNC-S1', 'MNC', 1, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('MNC-S2', 'MNC', 2, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('MNC-S3', 'MNC', 3, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('MNC-S4', 'MNC', 4, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('MNC-S5', 'MNC', 5, 60) ON CONFLICT (batch_code) DO NOTHING;
INSERT INTO student_batch (batch_code, program, semester, batch_size) VALUES ('MNC-S6', 'MNC', 6, 60) ON CONFLICT (batch_code) DO NOTHING;

-- faculty_course_map
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'AG' AND c.code = 'ED112' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'AJ' AND c.code = 'CT303' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'AKM' AND c.code = 'IT227' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'AKR' AND c.code = 'IC101' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'AM' AND c.code = 'PC110' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'AMM' AND c.code = 'IE411' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'AR' AND c.code = 'CS201' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'AR' AND c.code = 'CS302' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'AR2' AND c.code = 'IT205' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'AT' AND c.code = 'SC223' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'AT2' AND c.code = 'MC213' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'AT2' AND c.code = 'SC205' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'BC' AND c.code = 'CS301' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'BG' AND c.code = 'IT112' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'BK' AND c.code = 'HM106' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'BM' AND c.code = 'EL203' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'CJ' AND c.code = 'HM116' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'DKG' AND c.code = 'CT303' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'GD' AND c.code = 'SC217' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'GP' AND c.code = 'MC221' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'GS' AND c.code = 'HM116' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'GS' AND c.code = 'MC314' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'HP' AND c.code = 'CT204' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'MK' AND c.code = 'IE404' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'MK' AND c.code = 'IT112' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'MK2' AND c.code = 'IE402' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'MK2' AND c.code = 'SC224' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'MKG' AND c.code = 'SC107' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'MKR' AND c.code = 'CS374' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'MKR' AND c.code = 'IE402' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'MKR' AND c.code = 'SC205' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'MS' AND c.code = 'MC125' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'MS' AND c.code = 'MC211' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'MS' AND c.code = 'SC224' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'MT' AND c.code = 'MC312' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'MVJ' AND c.code = 'IE406' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'NKS' AND c.code = 'MC222' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'NKS' AND c.code = 'MC311' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'PA' AND c.code = 'MC321' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'PB' AND c.code = 'IT216' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'PB' AND c.code = 'MC223' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'PK' AND c.code = 'CT204' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'PK' AND c.code = 'IC121' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'PK2' AND c.code = 'ED111' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'PK2' AND c.code = 'ED121' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'PK2' AND c.code = 'MC313' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'PKS' AND c.code = 'IE403' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'PKS' AND c.code = 'IT304' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'PMJ' AND c.code = 'IT214' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'PhD Scholar' AND c.code = 'IT206' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'RC' AND c.code = 'MC212' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'RG' AND c.code = 'MC226' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'RLD' AND c.code = 'EL111' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'RLD' AND c.code = 'IE408' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'RM' AND c.code = 'IT422' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'RM' AND c.code = 'SC223' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'RM2' AND c.code = 'MC124' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'RP' AND c.code = 'MC112' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'SB' AND c.code = 'IT227' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'SB2' AND c.code = 'MC215' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'SB2' AND c.code = 'SC107' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'SDG' AND c.code = 'IT205' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'SJ' AND c.code = 'HM216' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'SK' AND c.code = 'MC216' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'SK' AND c.code = 'MC225' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'SM' AND c.code = 'EL111' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'SM' AND c.code = 'IE406' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'SP' AND c.code = 'IT216' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'SP' AND c.code = 'MC123' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'SR' AND c.code = 'IC121' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'SR' AND c.code = 'MC116' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'SS' AND c.code = 'IE411' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'SS' AND c.code = 'MC214' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'ST' AND c.code = 'IT314' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'TBD' AND c.code = 'MC122' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'TKM' AND c.code = 'IE410' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'VS' AND c.code = 'MC111' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'VS' AND c.code = 'MC224' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'VSP' AND c.code = 'IE407' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'YA' AND c.code = 'EL203' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'YV' AND c.code = 'CT216' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);
INSERT INTO faculty_course_map (faculty_id, course_id) SELECT f.faculty_id, c.course_id FROM faculty f, course c WHERE f.short_name = 'YV' AND c.code = 'SC407' AND NOT EXISTS (SELECT 1 FROM faculty_course_map m WHERE m.faculty_id = f.faculty_id AND m.course_id = c.course_id);

-- batch_course_map
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S1' AND c.code = 'IC101' AND f.short_name = 'AKR' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S1' AND c.code = 'EL111' AND f.short_name = 'SM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S1' AND c.code = 'IT112' AND f.short_name = 'BG' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S1' AND c.code = 'SC107' AND f.short_name = 'MKG' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S1' AND c.code = 'PC110' AND f.short_name = 'AM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S1' AND c.code = 'IC101' AND f.short_name = 'AKR' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S1' AND c.code = 'EL111' AND f.short_name = 'RLD' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S1' AND c.code = 'PC110' AND f.short_name = 'AM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S1' AND c.code = 'IT112' AND f.short_name = 'MK' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S1' AND c.code = 'SC107' AND f.short_name = 'SB2' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S1' AND c.code = 'PC110' AND f.short_name = 'AM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S1' AND c.code = 'MC111' AND f.short_name = 'VS' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S1' AND c.code = 'MC112' AND f.short_name = 'RP' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S1' AND c.code = 'MC116' AND f.short_name = 'SR' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S1' AND c.code = 'MC123' AND f.short_name = 'SP' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'EVD-S1' AND c.code = 'PC110' AND f.short_name = 'AM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'EVD-S1' AND c.code = 'EL111' AND f.short_name = 'RLD' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'EVD-S1' AND c.code = 'ED111' AND f.short_name = 'PK2' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'EVD-S1' AND c.code = 'IT112' AND f.short_name = 'MK' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'EVD-S1' AND c.code = 'ED112' AND f.short_name = 'AG' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S3' AND c.code = 'CT204' AND f.short_name = 'HP' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S3' AND c.code = 'IT216' AND f.short_name = 'PB' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S3' AND c.code = 'IT227' AND f.short_name = 'AKM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S3' AND c.code = 'SC223' AND f.short_name = 'AT' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S3' AND c.code = 'HM216' AND f.short_name = 'SJ' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S3' AND c.code = 'CT204' AND f.short_name = 'PK' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S3' AND c.code = 'IT216' AND f.short_name = 'SP' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S3' AND c.code = 'IT227' AND f.short_name = 'SB' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S3' AND c.code = 'SC223' AND f.short_name = 'RM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S3' AND c.code = 'HM216' AND f.short_name = 'SJ' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S3' AND c.code = 'CT204' AND f.short_name = 'PK' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S3' AND c.code = 'IT216' AND f.short_name = 'SP' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S3' AND c.code = 'IT227' AND f.short_name = 'SB' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S3' AND c.code = 'SC223' AND f.short_name = 'RM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'EVD-S3' AND c.code = 'HM216' AND f.short_name = 'SJ' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S3' AND c.code = 'HM216' AND f.short_name = 'SJ' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S3' AND c.code = 'MC211' AND f.short_name = 'MS' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S3' AND c.code = 'MC212' AND f.short_name = 'RC' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S3' AND c.code = 'MC213' AND f.short_name = 'AT2' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S3' AND c.code = 'MC214' AND f.short_name = 'SS' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S3' AND c.code = 'MC216' AND f.short_name = 'SK' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S5' AND c.code = 'IT314' AND f.short_name = 'ST' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S5' AND c.code = 'IT304' AND f.short_name = 'PKS' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S5' AND c.code = 'CT303' AND f.short_name = 'AJ' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S5' AND c.code = 'IT314' AND f.short_name = 'ST' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S5' AND c.code = 'IT304' AND f.short_name = 'PKS' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S5' AND c.code = 'CT303' AND f.short_name = 'DKG' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S5' AND c.code = 'IT314' AND f.short_name = 'ST' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S5' AND c.code = 'IT304' AND f.short_name = 'PKS' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S5' AND c.code = 'CT303' AND f.short_name = 'DKG' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S5' AND c.code = 'CS374' AND f.short_name = 'MKR' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S5' AND c.code = 'MC311' AND f.short_name = 'NKS' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S5' AND c.code = 'MC312' AND f.short_name = 'MT' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S5' AND c.code = 'MC313' AND f.short_name = 'PK2' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S5' AND c.code = 'MC314' AND f.short_name = 'GS' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S5' AND c.code = 'IE402' AND f.short_name = 'MK2' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S5' AND c.code = 'IE411' AND f.short_name = 'SS' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S5' AND c.code = 'IE407' AND f.short_name = 'VSP' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S5' AND c.code = 'IE406' AND f.short_name = 'MVJ' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S5' AND c.code = 'IE408' AND f.short_name = 'RLD' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S5' AND c.code = 'IE402' AND f.short_name = 'MK2' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S5' AND c.code = 'IE411' AND f.short_name = 'SS' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S5' AND c.code = 'IE407' AND f.short_name = 'VSP' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S5' AND c.code = 'IE406' AND f.short_name = 'MVJ' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S5' AND c.code = 'IE408' AND f.short_name = 'RLD' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S5' AND c.code = 'IE402' AND f.short_name = 'MK2' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S5' AND c.code = 'IE411' AND f.short_name = 'SS' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S5' AND c.code = 'IE407' AND f.short_name = 'VSP' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S5' AND c.code = 'IE406' AND f.short_name = 'MVJ' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S5' AND c.code = 'IE408' AND f.short_name = 'RLD' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S2' AND c.code = 'HM106' AND f.short_name = 'BK' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S2' AND c.code = 'HM106' AND f.short_name = 'BK' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S2' AND c.code = 'HM106' AND f.short_name = 'BK' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S2' AND c.code = 'HM106' AND f.short_name = 'BK' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'EVD-S2' AND c.code = 'HM106' AND f.short_name = 'BK' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S2' AND c.code = 'IC121' AND f.short_name = 'SR' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S2' AND c.code = 'IT205' AND f.short_name = 'SDG' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S2' AND c.code = 'IT206' AND f.short_name = 'PhD Scholar' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S2' AND c.code = 'SC205' AND f.short_name = 'AT2' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S2' AND c.code = 'SC217' AND f.short_name = 'GD' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S2' AND c.code = 'IC121' AND f.short_name = 'PK' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S2' AND c.code = 'IT205' AND f.short_name = 'AR2' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S2' AND c.code = 'IT206' AND f.short_name = 'PhD Scholar' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S2' AND c.code = 'SC205' AND f.short_name = 'MKR' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S2' AND c.code = 'SC217' AND f.short_name = 'GD' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S2' AND c.code = 'IC121' AND f.short_name = 'PK' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S2' AND c.code = 'IT205' AND f.short_name = 'AR2' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S2' AND c.code = 'IT206' AND f.short_name = 'PhD Scholar' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S2' AND c.code = 'SC205' AND f.short_name = 'MKR' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S2' AND c.code = 'SC217' AND f.short_name = 'GD' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S2' AND c.code = 'MC215' AND f.short_name = 'SB2' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S2' AND c.code = 'MC122' AND f.short_name = 'TBD' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S2' AND c.code = 'MC125' AND f.short_name = 'MS' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S2' AND c.code = 'MC124' AND f.short_name = 'RM2' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'EVD-S2' AND c.code = 'ED121' AND f.short_name = 'PK2' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'EVD-S2' AND c.code = 'IC121' AND f.short_name = 'PK' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'EVD-S2' AND c.code = 'IT205' AND f.short_name = 'AR2' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'EVD-S2' AND c.code = 'IT206' AND f.short_name = 'PhD Scholar' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'EVD-S2' AND c.code = 'SC217' AND f.short_name = 'GD' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S4' AND c.code = 'HM116' AND f.short_name = 'GS' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S4' AND c.code = 'EL203' AND f.short_name = 'BM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S4' AND c.code = 'IT214' AND f.short_name = 'PMJ' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S4' AND c.code = 'CT216' AND f.short_name = 'YV' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S4' AND c.code = 'SC224' AND f.short_name = 'MS' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S4' AND c.code = 'IT422' AND f.short_name = 'RM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S4' AND c.code = 'IE402' AND f.short_name = 'MKR' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S4' AND c.code = 'IE410' AND f.short_name = 'TKM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S4' AND c.code = 'HM116' AND f.short_name = 'CJ' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S4' AND c.code = 'EL203' AND f.short_name = 'YA' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S4' AND c.code = 'IT214' AND f.short_name = 'PMJ' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S4' AND c.code = 'CT216' AND f.short_name = 'YV' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S4' AND c.code = 'SC224' AND f.short_name = 'MK2' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S4' AND c.code = 'IT422' AND f.short_name = 'RM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S4' AND c.code = 'IE402' AND f.short_name = 'MKR' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S4' AND c.code = 'IE410' AND f.short_name = 'TKM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S4' AND c.code = 'HM116' AND f.short_name = 'CJ' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S4' AND c.code = 'EL203' AND f.short_name = 'YA' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S4' AND c.code = 'IT214' AND f.short_name = 'PMJ' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S4' AND c.code = 'CT216' AND f.short_name = 'YV' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S4' AND c.code = 'SC224' AND f.short_name = 'MK2' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S4' AND c.code = 'IT422' AND f.short_name = 'RM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S4' AND c.code = 'IE402' AND f.short_name = 'MKR' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S4' AND c.code = 'IE410' AND f.short_name = 'TKM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S4' AND c.code = 'CS201' AND f.short_name = 'AR' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S4' AND c.code = 'MC221' AND f.short_name = 'GP' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S4' AND c.code = 'MC222' AND f.short_name = 'NKS' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S4' AND c.code = 'MC223' AND f.short_name = 'PB' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S4' AND c.code = 'MC224' AND f.short_name = 'VS' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S4' AND c.code = 'MC225' AND f.short_name = 'SK' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S4' AND c.code = 'MC226' AND f.short_name = 'RG' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S6' AND c.code = 'SC407' AND f.short_name = 'YV' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S6' AND c.code = 'IE406' AND f.short_name = 'SM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S6' AND c.code = 'IE410' AND f.short_name = 'TKM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S6' AND c.code = 'IE411' AND f.short_name = 'AMM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S6' AND c.code = 'IE403' AND f.short_name = 'PKS' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTA-S6' AND c.code = 'IE404' AND f.short_name = 'MK' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S6' AND c.code = 'SC407' AND f.short_name = 'YV' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S6' AND c.code = 'IE406' AND f.short_name = 'SM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S6' AND c.code = 'IE410' AND f.short_name = 'TKM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S6' AND c.code = 'IE411' AND f.short_name = 'AMM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S6' AND c.code = 'IE403' AND f.short_name = 'PKS' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'ICTB-S6' AND c.code = 'IE404' AND f.short_name = 'MK' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S6' AND c.code = 'SC407' AND f.short_name = 'YV' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S6' AND c.code = 'IE406' AND f.short_name = 'SM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S6' AND c.code = 'IE410' AND f.short_name = 'TKM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S6' AND c.code = 'IE411' AND f.short_name = 'AMM' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S6' AND c.code = 'IE403' AND f.short_name = 'PKS' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S6' AND c.code = 'IE404' AND f.short_name = 'MK' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S6' AND c.code = 'CS302' AND f.short_name = 'AR' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'CS-S6' AND c.code = 'CS301' AND f.short_name = 'BC' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
INSERT INTO batch_course_map (batch_id, course_id, faculty_id) SELECT sb.batch_id, c.course_id, f.faculty_id FROM student_batch sb, course c, faculty f WHERE sb.batch_code = 'MNC-S6' AND c.code = 'MC321' AND f.short_name = 'PA' ON CONFLICT (batch_id, course_id) DO UPDATE SET faculty_id = EXCLUDED.faculty_id;
